name: CI

on:
  push:
  workflow_dispatch:

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      env:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: Metratrj/learn-tdd
